title: Harry Cho's Personal Blog 
description: > # this means to ignore newlines until "baseurl:"
  This is Harry Cho's personal blog powered by Jekyll & github page.
  In this blog, I will talk about my daily life as well as my interest towards technical stuff, such as AR, VR, machine learning and etc.
  Thanks for visiting my blog, and hope you enjoy the reading.   
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hyunmin Cho # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a product & service planner focusing on fast prototyping. I'm always open to exploring new opportunity and to learning.
facebook: jo121jo # add your Facebook handle
github: HarryCho # add your Github handle
# linkedin: # add your Linkedin handle
# email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
